// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLbGHcjzu-iAeafnqjw7_QJp9ux7EgWRI',
    appId: '1:691702273307:web:907b4e01297329f8a72fbe',
    messagingSenderId: '691702273307',
    projectId: 'dev-turbo',
    authDomain: 'dev-turbo.firebaseapp.com',
    storageBucket: 'dev-turbo.appspot.com',
    measurementId: 'G-39N12BMHRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtPNFjMnA-ZYiYv0PKd3CEJ6ga_hnsMks',
    appId: '1:691702273307:android:9827619104ab9817a72fbe',
    messagingSenderId: '691702273307',
    projectId: 'dev-turbo',
    storageBucket: 'dev-turbo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWSXtceHr5TVRB50ofEUkhrRaoA1xA2T4',
    appId: '1:691702273307:ios:76360c843be7c0cea72fbe',
    messagingSenderId: '691702273307',
    projectId: 'dev-turbo',
    storageBucket: 'dev-turbo.appspot.com',
    iosClientId: '691702273307-e5oclt74h7fhhsuk7k8mlbjindpe61qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWSXtceHr5TVRB50ofEUkhrRaoA1xA2T4',
    appId: '1:691702273307:ios:76360c843be7c0cea72fbe',
    messagingSenderId: '691702273307',
    projectId: 'dev-turbo',
    storageBucket: 'dev-turbo.appspot.com',
    iosClientId: '691702273307-e5oclt74h7fhhsuk7k8mlbjindpe61qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationalApp',
  );
}
